openapi: 3.0.3
info:
  title: Skill Step Update API (PATCH extension)
  description: |
    002 で PATCH /api/skill/step/[stepId] を拡張。
    既存の done に加え、status（scheduled|done|missed|skipped）と scheduledDate を更新可能にする。
    status を skipped にした場合は、当該 goal に対して runReschedule を 1 回実行する。
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development
  - url: https://your-domain.vercel.app
    description: Production

paths:
  /api/skill/step/{stepId}:
    patch:
      summary: Update step (completion, status, scheduled date)
      description: |
        - done: 001 互換。完了フラグ。
        - status: 002 追加。scheduled | done | missed | skipped。
        - scheduledDate: 002 追加。YYYY-MM-DD。手動で予定日を変える場合に使用。
        status を skipped にすると、同じ goal の未達・スキップ繰り越しを実行する。
      operationId: patchStep
      tags:
        - Skill
        - Plan
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
            minLength: 1
          description: Step ID (Firestore document ID)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StepUpdateRequest'
            examples:
              completion:
                summary: Mark complete (001 compatible)
                value:
                  done: true
              skip:
                summary: Skip (002)
                value:
                  status: skipped
              rescheduleManual:
                summary: Manually change scheduled date
                value:
                  scheduledDate: '2025-01-28'
      responses:
        '200':
          description: Step updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StepUpdateResponse'
        '400':
          description: Validation error (invalid status, date, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Step not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error (Firestore, reschedule)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    StepUpdateRequest:
      type: object
      minProperties: 1
      properties:
        done:
          type: boolean
          description: Completion flag (001 compatible)
        status:
          type: string
          enum: [scheduled, done, missed, skipped]
          description: Schedule status (002)
        scheduledDate:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: YYYY-MM-DD (002)
    StepUpdateResponse:
      type: object
      required:
        - stepId
        - ok
      properties:
        stepId:
          type: string
        ok:
          type: boolean
          example: true
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
